import { db } from "./index";
import { grants, installers, states } from "./schema";
import { US_STATES } from "../utils/constants";

const SEED_GRANTS = [
  // Federal Programs
  {
    title: "National Electric Vehicle Infrastructure (NEVI) Formula Program",
    slug: "nevi-formula-program",
    description: "The NEVI Formula Program provides $5 billion to states to strategically deploy EV charging infrastructure along designated Alternative Fuel Corridors. Funds are distributed via formula to all 50 states, DC, and Puerto Rico to build out a national charging network.",
    amountMin: 100000000,
    amountMax: 500000000000,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.fhwa.dot.gov/environment/alternative_fuel_corridors/nominations/90d_nevi_formula_program_guidance.pdf",
    funder: "Federal Highway Administration (FHWA)",
    jurisdiction: "federal" as const,
    state: null,
    city: null,
    utility: null,
    eligibleEntities: ["municipality", "commercial_fleet", "transit_agency"],
    eligibleHardware: ["dcfc"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
  {
    title: "Charging and Fueling Infrastructure (CFI) Discretionary Grant Program",
    slug: "cfi-discretionary-grant-program",
    description: "A $2.5 billion competitive grant program to deploy EV charging and alternative fueling infrastructure in publicly accessible locations. Divided into Community Charging and Corridor Charging grants for urban and highway deployment.",
    amountMin: 50000000,
    amountMax: 132120000000,
    deadline: "2026-09-30",
    status: "active" as const,
    sourceUrl: "https://www.transportation.gov/rural/grant-toolkit/charging-and-fueling-infrastructure-grant-program",
    funder: "U.S. Department of Transportation",
    jurisdiction: "federal" as const,
    state: null,
    city: null,
    utility: null,
    eligibleEntities: ["municipality", "commercial_fleet", "transit_agency", "school_district", "nonprofit"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
  {
    title: "Alternative Fuel Vehicle Refueling Property Tax Credit (30C)",
    slug: "federal-30c-tax-credit",
    description: "A federal tax credit covering 30% of the cost of installing qualified EV charging equipment, up to $100,000 per property for commercial installations. Extended through 2032 by the Inflation Reduction Act. Property must be in an eligible census tract.",
    amountMin: null,
    amountMax: 10000000,
    deadline: "2032-12-31",
    status: "active" as const,
    sourceUrl: "https://afdc.energy.gov/laws/10513",
    funder: "Internal Revenue Service (IRS)",
    jurisdiction: "federal" as const,
    state: null,
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "workplace", "multi_unit_dwelling"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "tax_credit" as const,
    justice40: true,
    source: "manual",
  },
  {
    title: "Clean School Bus Program",
    slug: "epa-clean-school-bus-program",
    description: "EPA program providing $5 billion to replace existing school buses with zero-emission and clean school buses. Includes funding for charging infrastructure at school bus depots.",
    amountMin: 25000000,
    amountMax: 37500000,
    deadline: "2026-08-15",
    status: "active" as const,
    sourceUrl: "https://www.epa.gov/cleanschoolbus",
    funder: "Environmental Protection Agency (EPA)",
    jurisdiction: "federal" as const,
    state: null,
    city: null,
    utility: null,
    eligibleEntities: ["school_district"],
    eligibleHardware: ["dcfc", "level_2"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
  // California
  {
    title: "California Energy Commission — EnergIIZE Commercial Fleet",
    slug: "california-energiize-commercial-fleet",
    description: "The EnergIIZE program provides incentives for zero-emission vehicle infrastructure for medium- and heavy-duty vehicles. Funding covers charging and hydrogen fueling equipment for commercial fleets operating in California.",
    amountMin: 5000000,
    amountMax: 50000000,
    deadline: "2026-12-31",
    status: "active" as const,
    sourceUrl: "https://energiize.org/",
    funder: "California Energy Commission (CEC)",
    jurisdiction: "state" as const,
    state: "CA",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "transit_agency"],
    eligibleHardware: ["dcfc"],
    incentiveType: "grant" as const,
    justice40: false,
    source: "manual",
  },
  {
    title: "California LCFS Holdback — EV Charging Infrastructure",
    slug: "california-lcfs-holdback",
    description: "The Low Carbon Fuel Standard program generates credits for EV charging stations. Station operators can earn and sell LCFS credits based on electricity dispensed, providing ongoing revenue to offset infrastructure costs.",
    amountMin: null,
    amountMax: null,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://ww2.arb.ca.gov/our-work/programs/low-carbon-fuel-standard",
    funder: "California Air Resources Board (CARB)",
    jurisdiction: "state" as const,
    state: "CA",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "workplace"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "rebate" as const,
    justice40: false,
    source: "manual",
  },
  {
    title: "LADWP Commercial EV Charger Rebate Program",
    slug: "ladwp-commercial-ev-charger-rebate",
    description: "LADWP offers tiered rebates for commercial EV charger installations: Tier 1 (50-149 kW) up to $20,000 per charger, Tier 2 (150-274 kW) up to $60,000 per charger, Tier 3 (275+ kW) up to $100,000 per charger. Enhanced rebates for installations in disadvantaged communities.",
    amountMin: 2000000,
    amountMax: 12500000,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.ladwp.com/commercial-services/programs-and-rebates-commercial/commercial-ev-charging/commercial-ev-charger-rebate-program",
    funder: "Los Angeles Department of Water and Power (LADWP)",
    jurisdiction: "utility" as const,
    state: "CA",
    city: "Los Angeles",
    utility: "LADWP",
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "multi_unit_dwelling", "workplace"],
    eligibleHardware: ["dcfc"],
    incentiveType: "rebate" as const,
    justice40: true,
    source: "manual",
  },
  {
    title: "SCE Charge Ready Transport Program",
    slug: "sce-charge-ready-transport",
    description: "Southern California Edison provides make-ready infrastructure for medium and heavy-duty fleet charging. SCE designs, installs, owns, and maintains the electrical infrastructure from the grid to the charger. Fleet operators only need to purchase and install the chargers.",
    amountMin: null,
    amountMax: null,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.sce.com/business/electric-cars/charge-ready-transport",
    funder: "Southern California Edison (SCE)",
    jurisdiction: "utility" as const,
    state: "CA",
    city: null,
    utility: "SCE",
    eligibleEntities: ["commercial_fleet", "transit_agency", "school_district"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "make_ready" as const,
    justice40: false,
    source: "manual",
  },
  // New York
  {
    title: "New York Truck Voucher Incentive Program (NYTVIP)",
    slug: "new-york-truck-voucher-incentive-program",
    description: "NYTVIP provides vouchers toward the incremental cost of purchasing or leasing zero-emission medium and heavy-duty vehicles, including funding for associated charging infrastructure. Additional funding available for fleets in disadvantaged communities.",
    amountMin: 5000000,
    amountMax: 18500000,
    deadline: "2026-06-30",
    status: "active" as const,
    sourceUrl: "https://www.nyserda.ny.gov/All-Programs/Truck-Voucher-Program",
    funder: "New York State Energy Research and Development Authority (NYSERDA)",
    jurisdiction: "state" as const,
    state: "NY",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "municipality", "transit_agency"],
    eligibleHardware: ["dcfc", "level_2"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
  {
    title: "Con Edison EV Make-Ready Program",
    slug: "con-edison-ev-make-ready",
    description: "Con Edison covers 100% of the make-ready infrastructure costs for Level 2 and DCFC installations in their service territory. Covers electrical work from the grid to the charger location including panels, conduit, and wiring.",
    amountMin: null,
    amountMax: null,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.coned.com/en/our-energy-future/technology-innovation/electric-vehicles",
    funder: "Consolidated Edison (Con Edison)",
    jurisdiction: "utility" as const,
    state: "NY",
    city: "New York",
    utility: "Con Edison",
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "multi_unit_dwelling", "workplace"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "make_ready" as const,
    justice40: false,
    source: "manual",
  },
  // Texas
  {
    title: "Texas Volkswagen Environmental Mitigation Program — DC Fast Charging",
    slug: "texas-vw-mitigation-dcfc",
    description: "Texas Commission on Environmental Quality administers VW settlement funds for deploying DCFC infrastructure across Texas. Competitive grants for publicly accessible charging stations along major corridors.",
    amountMin: 10000000,
    amountMax: 50000000,
    deadline: "2026-10-01",
    status: "active" as const,
    sourceUrl: "https://www.tceq.texas.gov/airquality/terp/vw",
    funder: "Texas Commission on Environmental Quality (TCEQ)",
    jurisdiction: "state" as const,
    state: "TX",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "municipality", "commercial_real_estate"],
    eligibleHardware: ["dcfc"],
    incentiveType: "grant" as const,
    justice40: false,
    source: "manual",
  },
  {
    title: "Texas TERP — Light-Duty Motor Vehicle Purchase or Lease Incentive",
    slug: "texas-terp-light-duty-incentive",
    description: "The Texas Emissions Reduction Plan provides grants for the purchase or lease of new light-duty electric vehicles and associated charging infrastructure for qualifying fleets.",
    amountMin: 250000,
    amountMax: 500000,
    deadline: "2026-05-31",
    status: "active" as const,
    sourceUrl: "https://www.tceq.texas.gov/airquality/terp",
    funder: "Texas Commission on Environmental Quality (TCEQ)",
    jurisdiction: "state" as const,
    state: "TX",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "municipality"],
    eligibleHardware: ["level_2"],
    incentiveType: "grant" as const,
    justice40: false,
    source: "manual",
  },
  // Massachusetts
  {
    title: "MassDEP Fleet EV Charging Deployment Grant Program 3.0",
    slug: "massdep-fleet-ev-charging-deployment-3",
    description: "Massachusetts Department of Environmental Protection provides grants for workplace and fleet EV charging installation. Covers Level 2 and DCFC infrastructure for municipal, state, and commercial fleets.",
    amountMin: 5000000,
    amountMax: 50000000,
    deadline: "2026-07-15",
    status: "active" as const,
    sourceUrl: "https://www.mass.gov/info-details/fleet-ev-charging-deployment-grant-program-30",
    funder: "Massachusetts Department of Environmental Protection (MassDEP)",
    jurisdiction: "state" as const,
    state: "MA",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "municipality", "school_district", "transit_agency"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "grant" as const,
    justice40: false,
    source: "manual",
  },
  {
    title: "National Grid — EV Charging Station Program (MA)",
    slug: "national-grid-ma-ev-charging",
    description: "National Grid offers rebates for commercial and fleet EV charging installations in their Massachusetts service territory. Covers a portion of equipment and installation costs for Level 2 and DCFC stations.",
    amountMin: 250000,
    amountMax: 5000000,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.nationalgridus.com/MA-Business/Energy-Saving-Programs/Electric-Vehicle-Charging-Station-Program",
    funder: "National Grid",
    jurisdiction: "utility" as const,
    state: "MA",
    city: null,
    utility: "National Grid",
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "workplace", "multi_unit_dwelling"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "rebate" as const,
    justice40: false,
    source: "manual",
  },
  // Illinois
  {
    title: "Illinois EPA Diesel Emissions Reduction Grant — EV Infrastructure",
    slug: "illinois-epa-diesel-reduction-ev",
    description: "Illinois EPA provides competitive grants for replacing diesel vehicles and equipment with zero-emission alternatives, including funding for EV charging infrastructure at fleet depots.",
    amountMin: 5000000,
    amountMax: 25000000,
    deadline: "2026-11-30",
    status: "active" as const,
    sourceUrl: "https://epa.illinois.gov/topics/air-quality/mobile-sources/diesel-emissions.html",
    funder: "Illinois Environmental Protection Agency",
    jurisdiction: "state" as const,
    state: "IL",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "municipality", "school_district"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "grant" as const,
    justice40: false,
    source: "manual",
  },
  {
    title: "ComEd EV Charging Rebate Program",
    slug: "comed-ev-charging-rebate",
    description: "Commonwealth Edison offers rebates for installing Level 2 and DCFC charging stations in their northern Illinois service territory. Higher rebates available for installations in underserved communities.",
    amountMin: 200000,
    amountMax: 5000000,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.comed.com/SmartEnergy/InnovationTechnology/Pages/ElectricVehicles.aspx",
    funder: "Commonwealth Edison (ComEd)",
    jurisdiction: "utility" as const,
    state: "IL",
    city: null,
    utility: "ComEd",
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "workplace", "multi_unit_dwelling"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "rebate" as const,
    justice40: true,
    source: "manual",
  },
  // Colorado
  {
    title: "Colorado Charge Ahead Program",
    slug: "colorado-charge-ahead",
    description: "Colorado Energy Office program providing grants for workplace, multi-unit dwelling, and fleet EV charging. Higher funding available for installations in disproportionately impacted communities.",
    amountMin: 500000,
    amountMax: 3500000,
    deadline: "2026-04-30",
    status: "active" as const,
    sourceUrl: "https://energyoffice.colorado.gov/transportation/grants-incentives/charge-ahead-colorado",
    funder: "Colorado Energy Office",
    jurisdiction: "state" as const,
    state: "CO",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "workplace", "multi_unit_dwelling"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
  // Washington
  {
    title: "Washington State Department of Commerce — EV Charging Infrastructure",
    slug: "washington-commerce-ev-charging",
    description: "Washington state provides grants and technical assistance for deploying EV charging infrastructure. Priority given to rural areas, underserved communities, and fleet electrification projects.",
    amountMin: 5000000,
    amountMax: 25000000,
    deadline: "2026-08-01",
    status: "active" as const,
    sourceUrl: "https://www.commerce.wa.gov/growing-the-economy/energy/clean-energy-fund/",
    funder: "Washington State Department of Commerce",
    jurisdiction: "state" as const,
    state: "WA",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "municipality", "transit_agency", "school_district"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
  // Oregon
  {
    title: "Oregon Clean Fuels Program — EV Charging Credits",
    slug: "oregon-clean-fuels-ev-credits",
    description: "Oregon's Clean Fuels Program allows EV charging station operators to generate and sell credits based on electricity dispensed. Provides ongoing revenue stream to offset installation and operating costs.",
    amountMin: null,
    amountMax: null,
    deadline: null,
    status: "active" as const,
    sourceUrl: "https://www.oregon.gov/deq/ghgp/cfp/pages/default.aspx",
    funder: "Oregon Department of Environmental Quality",
    jurisdiction: "state" as const,
    state: "OR",
    city: null,
    utility: null,
    eligibleEntities: ["commercial_fleet", "commercial_real_estate", "workplace"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "rebate" as const,
    justice40: false,
    source: "manual",
  },
  // Archived example
  {
    title: "FY2024 CFI Community Charging Grants",
    slug: "fy2024-cfi-community-charging",
    description: "Fiscal Year 2024 round of CFI Community Charging grants. This funding round has closed. Applications were accepted for deploying EV charging in community locations such as schools, parks, and public buildings.",
    amountMin: 50000000,
    amountMax: 100000000000,
    deadline: "2024-09-11",
    status: "archived" as const,
    sourceUrl: "https://www.transportation.gov/rural/grant-toolkit/charging-and-fueling-infrastructure-grant-program",
    funder: "U.S. Department of Transportation",
    jurisdiction: "federal" as const,
    state: null,
    city: null,
    utility: null,
    eligibleEntities: ["municipality", "school_district", "nonprofit", "tribal"],
    eligibleHardware: ["level_2", "dcfc"],
    incentiveType: "grant" as const,
    justice40: true,
    source: "manual",
  },
];

const SEED_INSTALLERS = [
  {
    companyName: "ChargePoint Commercial Services",
    slug: "chargepoint-commercial-services",
    description: "Leading EVSE installer specializing in commercial fleet charging infrastructure. Handles complete turnkey solutions from site assessment through procurement, installation, and ongoing maintenance. Certified for Level 2 and DCFC installations.",
    phone: "(555) 100-2000",
    email: "commercial@example-chargepoint.com",
    serviceAreas: ["CA", "NY", "TX", "IL", "WA"],
    hardwareTypes: ["level_2", "dcfc"],
    tier: "premium" as const,
    verified: true,
  },
  {
    companyName: "GreenFleet Electric",
    slug: "greenfleet-electric",
    description: "Specialized in municipal and transit fleet electrification. Expert in grant compliance documentation and utility coordination. Serving the Northeast corridor with Level 2 and DCFC installations.",
    phone: "(555) 200-3000",
    email: "info@example-greenfleet.com",
    serviceAreas: ["NY", "MA", "CT", "NJ", "PA"],
    hardwareTypes: ["level_2", "dcfc"],
    tier: "premium" as const,
    verified: true,
  },
  {
    companyName: "SunPower EV Infrastructure",
    slug: "sunpower-ev-infrastructure",
    description: "Combined solar and EV charging solutions for commercial properties. Specializes in DCFC installations with on-site solar generation to minimize demand charges and maximize ROI.",
    phone: "(555) 300-4000",
    email: "info@example-sunpowerev.com",
    serviceAreas: ["CA", "AZ", "NV", "CO"],
    hardwareTypes: ["dcfc"],
    tier: "free" as const,
    verified: true,
  },
  {
    companyName: "Midwest Charge Solutions",
    slug: "midwest-charge-solutions",
    description: "Regional EV charging installer covering the Midwest. Expert in fleet depot charging, workplace installations, and utility rebate program navigation. Fast turnaround on Level 2 commercial projects.",
    phone: "(555) 400-5000",
    email: "info@example-midwestcharge.com",
    serviceAreas: ["IL", "WI", "MI", "IN", "OH"],
    hardwareTypes: ["level_2", "dcfc"],
    tier: "free" as const,
    verified: true,
  },
  {
    companyName: "LoneStar EV Contractors",
    slug: "lonestar-ev-contractors",
    description: "Texas-based EVSE installation company specializing in commercial and fleet charging. Licensed electrical contractor with extensive experience in TCEQ grant-funded projects.",
    phone: "(555) 500-6000",
    email: "info@example-lonestarev.com",
    serviceAreas: ["TX", "OK", "LA"],
    hardwareTypes: ["level_2", "dcfc"],
    tier: "premium" as const,
    verified: true,
  },
];

async function seed() {
  console.log("Seeding database...");

  // Seed states
  console.log("Seeding states...");
  for (const state of US_STATES) {
    await db
      .insert(states)
      .values({ code: state.code, name: state.name, grantCount: 0 })
      .onConflictDoNothing();
  }

  // Seed grants
  console.log("Seeding grants...");
  for (const grant of SEED_GRANTS) {
    await db.insert(grants).values(grant).onConflictDoNothing();
  }

  // Seed installers
  console.log("Seeding installers...");
  for (const installer of SEED_INSTALLERS) {
    await db.insert(installers).values(installer).onConflictDoNothing();
  }

  // Update state grant counts
  console.log("Updating state grant counts...");
  for (const state of US_STATES) {
    const stateGrants = SEED_GRANTS.filter(
      (g) => g.state === state.code && g.status === "active"
    );
    if (stateGrants.length > 0) {
      await db
        .update(states)
        .set({ grantCount: stateGrants.length })
        .where(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          (await import("drizzle-orm")).eq(states.code as any, state.code)
        );
    }
  }

  console.log(
    `Seeded ${SEED_GRANTS.length} grants, ${SEED_INSTALLERS.length} installers, ${US_STATES.length} states.`
  );
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
